### ISSUE TITLE
Vuejs todo app tutorial

### ISSUE THREAD

**Issue by EzpieCo** [EzpieCo/ezpie#83]
If you know about vue and whould like to make a blog about how to make one simple todo app with it, you can add your blog here.

Follow along these steps in order to make your first blog post in ezpie:

- [ ] Create a file in `src/pages/blogs` give it a nice title like - _learn-vue-by-making-a-todo-app.md_
- [ ] Now copy paste this scrap of code in the top of the file:
    
    ```
    ---
    layout: ../../layout/PostLayout.astro
    title: One nice title
    description: give it a clean description. Can be the first para of your blog
    published: what's the date?
    author: you name
    permalink: /blogs/{the title}
   image: /images/thumbnail/{if you have one}.{any, svg is perferred}
    ---
    ```
- [ ] You can also add a thumbnail if you like, in the `public/images/thumbnail` svg is perferred
- [ ] **Make so content:** Now start writing what comes into your mind about how you can create a todo app just the same way you did the first time
- [ ] You can check how it looks by running `npm run dev`

If you have any issue or any idea that you may want to add just ask me. I will help you any moment you want 😄
